### PR TITLE
Add rel attribute to social links

### PR DESCRIPTION
**Pull request by luizbills**
- `rel="nofollow"` to improve SEO.
- `rel="me"` to tell Google that you're not just linking to those pages, but you actually control them. [reference](https://www.smartinsights.com/search-engine-optimisation-seo/index-inclusion/google-rel-me/)
- `rel="noopener"` for security.

### CODE REVIEW

**Comment by daviedR** [comment]
Hi Luiz,

The `rel="noopener"` is added along with `target="_blank"` when the "open new tab" option is set to "new tab". If you want to use `rel="me nofollow noopener"` in all conditions, I think we should remove the `rel` attribute in the conditional tag.

**Comment by luizbills** [comment]
You're right. I had not noticed the other `rel`. Fixed.

**Comment by daviedR** [comment]
Hi @luizbills 

Sorry I made a mistake, can you recreate a pull request?

I am not really familiar with Git.

**Comment by luizbills** [comment]
No problem.

**Pull request merged**
